# Generated by Django 5.2.5 on 2025-08-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatrow',
            name='svg_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
