# Generated by Django 5.2.5 on 2025-08-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_event_image_event_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('screening', 'Screening'), ('meetings', 'Meetings'), ('performances', 'Performances'), ('workshops', 'Workshops'), ('exhibitions', 'Exhibitions'), ('music', 'Music Shows'), ('comedy', 'Comedy Shows'), ('awards', 'Award Shows')], default='screening', max_length=32),
        ),
    ]
