# Generated by Django 5.2.5 on 2025-08-27 08:33

import django.db.models.deletion
from django.db import migrations, models


def forwards_map_category(apps, schema_editor):
    Category = apps.get_model('tickets', 'Category')
    Event = apps.get_model('tickets', 'Event')

    # Ensure categories exist matching legacy strings
    legacy = [
        ('screening', 'Screening'),
        ('meetings', 'Meetings'),
        ('performances', 'Performances'),
        ('workshops', 'Workshops'),
        ('exhibitions', 'Exhibitions'),
        ('music', 'Music Shows'),
        ('comedy', 'Comedy Shows'),
        ('awards', 'Award Shows'),
    ]
    slug_map = {}
    for slug, name in legacy:
        obj, _ = Category.objects.get_or_create(name=name, defaults={'slug': slug})
        if not obj.slug:
            obj.slug = slug
            obj.save(update_fields=['slug'])
        slug_map[slug] = obj.id

    # Copy from old char field 'category' into new FK field 'category_fk'
    for ev in Event.objects.all():
        val = getattr(ev, 'category', None)  # legacy char value
        cat_id = slug_map.get(val)
        if cat_id:
            setattr(ev, 'category_fk_id', cat_id)
            ev.save(update_fields=['category_fk'])


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_event_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
            ],
        ),
        # Add a temporary FK field to migrate data
        migrations.AddField(
            model_name='event',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.category'),
        ),
        migrations.RunPython(forwards_map_category, migrations.RunPython.noop),
        # Remove legacy char field and rename FK
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='category_fk',
            new_name='category',
        ),
    ]
