# Generated by Django 5.2.5
from django.db import migrations, models


def forwards_copy_existing(apps, schema_editor):
    # If any events still have a 'category' FK column from older state, copy to M2M
    Event = apps.get_model('tickets', 'Event')
    Category = apps.get_model('tickets', 'Category')
    through_model = Event.categories.through
    # Try to add existing single category into m2m if attribute present
    if hasattr(Event, 'category_id'):
        for ev in Event.objects.all():
            if getattr(ev, 'category_id', None):
                try:
                    through_model.objects.get_or_create(event_id=ev.id, category_id=ev.category_id)
                except Exception:
                    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_category_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='events', to='tickets.category'),
        ),
        migrations.RunPython(forwards_copy_existing, migrations.RunPython.noop),
    ]

