# Generated by Django 5.2.5 on 2025-08-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_event_categories_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
    ]
